apiVersion: v1
kind: Pod
metadata:
  name: app-readinessprob
  labels:
    app: app-readinessprob
spec:
  containers:
    - name: app
      image: gcr.io/smartcity-gl/harmonic:v2.0.2
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 0
        periodSeconds: 2
        failureThreshold: 3
        successThreshold: 1