apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
spec:
  containers:
    - name: app
      image: gcr.io/k8s-k3s/demo:v1.0.0
      ports:
        - containerPort: 8000
      livenessProbe:
        httpGet:
          path: /health
          port: http
        initialDelaySeconds: 3
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3